# Generated by Django 3.2.6 on 2021-08-25 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicativo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresas',
            name='cnpj',
            field=models.IntegerField(max_length=14),
        ),
    ]
